CC ?= gcc
CFLAGS := -std=c99 -Wall -Wextra -Werror -O0 -g -Iinclude
LDFLAGS :=
ifeq ($(SAN),1)
CFLAGS += -fsanitize=address,undefined
LDFLAGS += -fsanitize=address,undefined
endif

SOURCES := {{ source_files | join(" ") }}
TARGETS := {{ target_names | join(" ") }}

.PHONY: all clean
all: $(TARGETS)

clean:
	rm -rf build
